### ISSUE TITLE
listening bar is not full witdh

### ISSUE THREAD

**Issue by IMBiXx** [NYRI4/Comfy-spicetify#1]
Hi,
The listening bar is not full width at all:

![image](https://user-images.githubusercontent.com/9751045/140747557-e13372c2-d6e3-4aaf-8194-2df767cb9de4.png)

**Comment by NYRI4** [comment]
I can't reproduce the issue on my client, you'll have to give more description, maybe try to disable some extensions to see if that could be the cause ?

**Comment by zaryavtre** [comment]
The same thing is happening on my end. Disabled all extensions.

**Comment by afonsojramos** [comment]
@IMBiXx @zaryavtre it is not happening on my end. Maybe update the theme? Also, can you share you config files?

**Comment by TheGeeKing** [comment]
@IMBiXx @zaryavtre any update on that issue? If you still encounter that issue, please send your config file.

**Comment by zaryavtre** [comment]
For me, you can close this issue now. After new updates it started working as expected.

**Comment by TheGeeKing** [comment]
@NYRI4 you can close this issue.
