### ISSUE TITLE
Listening bar is covered

### ISSUE THREAD

**Issue by xartuu** [NYRI4/Comfy-spicetify#14]
The `newPlayingBar` is covered by the `connectBar`.

Additionally, it would be nice if the green time indicator moved smoothly rather than skipping.

More screenshots [here](https://imgur.com/a/GMGYtze).

![Screen shot](https://i.imgur.com/D4mVG7L.png)

**Comment by NYRI4** [comment]
This should no longer be an issue in the last version of Comfy

**Comment by xartuu** [comment]
It looks so much better now! Thank you.
