### ISSUE TITLE
Cover song as background

### ISSUE THREAD

**Issue by xartuu** [NYRI4/Comfy-spicetify#15]
Please add a song overlay as background. The [DribbblishDynamic](https://github.com/JulienMaille/dribbblish-dynamic-theme) theme has something like this, I've used it before and it's great, but sometimes it stutters.

Fix the "Musixmatch" caption in the synced song lyrics still so there's no scrolling on that page, because it's annoying. Again, the DribbblishDynamic theme has this done.

Other than that very friendly theme, I like it a lot.

More screenshots [here](https://imgur.com/a/ke7U7w9).

![Screen shot](https://i.imgur.com/o3iH02J.png)

**Comment by NYRI4** [comment]
Done

**Comment by xartuu** [comment]
Could you still remove the scrolling on the Musixmatch song lyrics page?
