### ISSUE TITLE
Reddit app label/icon gets cut off in the sidebar

### ISSUE THREAD

**Issue by theRealPadster** [NYRI4/Comfy-spicetify#18]
I have no clue why this happens, but it doesn't happen with other themes 🤷
![image](https://user-images.githubusercontent.com/1565883/146665310-450597af-b2ff-4194-9c83-9c4ebf836a62.png)
![image](https://user-images.githubusercontent.com/1565883/146665342-979b510b-8d4b-44af-91c6-f9b45c604f0b.png)

**Comment by NYRI4** [comment]
I'm using CSS grids to do that, the first problem is that I need to reference every tabs and it looks like I didn't have a clue about the "Made for You" tab. The second problem, regardless of the actual issue is that I defined an order and that sidebar config sort feature can't work

**Comment by theRealPadster** [comment]
Ah, I didn't realize they were individually addressed. The "Made For You" thing is from the experimental features thing. I don't think I'm using sidebar config. 

![image](https://user-images.githubusercontent.com/1565883/147419486-07de6d97-67fe-4faf-b5de-57e93037c40a.png)

**Comment by theRealPadster** [comment]
Ohh, it's probably because I was messing with it a bit, and changed the name to "reddit-fork". It works again if I change the `data-id` and `href` back to "reddit" instead of "reddit-fork". 
![image](https://user-images.githubusercontent.com/1565883/147419573-db5848e1-e28f-4ff4-8c23-9327f5f911c6.png)
