### ISSUE TITLE
Collaborative playlists are broken

### ISSUE THREAD

**Issue by huhridge** [NYRI4/Comfy-spicetify#21]
Spicetify: 2.8.4
Spotify: 1.1.76

Collaborative playlists are displayed broken
![Screenshot 2022-01-09 at 14 05 32](https://user-images.githubusercontent.com/67046436/148675173-d6e200d8-96ec-4812-8bee-aa5dd428ff74.jpg)

**Comment by NYRI4** [comment]
This commit should do the job

**Comment by huhridge** [comment]
Thanks!
