### ISSUE TITLE
Default Button?

### ISSUE THREAD

**Issue by ZeraTS** [NYRI4/Comfy-spicetify#24]
Hello so my comfy spicetify theme works 100% fine! But my play button remains the default which kind of bothers me. Do you know a fix? 
![image](https://user-images.githubusercontent.com/51274450/150883069-18e2741b-4f75-47eb-8480-8999f8822e46.png)

**Comment by Jayy001** [comment]
There isn't a "fix", this is supposed to happen - how the theme was created. If you want it a customised one, then make a theme your-self / edit this one, or find another one.

**Comment by ZeraTS** [comment]
> There isn't a "fix", this is supposed to happen - how the theme was created. If you want it a customised one, then make a theme your-self / edit this one, or find another one. 

Yes however on the actual release image it represents a custom curved button for play. So I assume this isn't supposed to happen
