### ISSUE TITLE
The cover dosen't change when it changes the song

### ISSUE THREAD

**Issue by Thiagoedlp151** [NYRI4/Comfy-spicetify#3]
You have to go back and return to the playlist page to see the actual cover of the song.

![image](https://user-images.githubusercontent.com/84394684/141159091-0a81aaeb-43fc-4a85-9ed6-dc2b26a2b2f3.png)

**Comment by NYRI4** [comment]
I can't reproduce the issue on my client, you'll have to give more description, maybe try to disable some extensions to see if that could be the cause ?
