### ISSUE TITLE
User profile picture not aligned.

### ISSUE THREAD

**Issue by afonsojramos** [NYRI4/Comfy-spicetify#5]
![image](https://user-images.githubusercontent.com/19473034/142605223-7a61b154-b8a6-47c8-82a6-033a5ca463fa.png)

In my client the profile picture is not correctly scaled, is this expected at the moment?

**Comment by NYRI4** [comment]
This should be now fixed : https://github.com/NYRI4/Comfy-spicetify/commit/efe61dc4f80091628aae3b7f9adda5c2bbd0127d

**Comment by afonsojramos** [comment]
I'd say that it is worse now 😅 The problem is that my image is not square in itself I guess 🤷 
![image](https://user-images.githubusercontent.com/19473034/142735684-5eed3a6a-8dbc-4b39-a434-ffd2b1d84ad5.png)

**Comment by afonsojramos** [comment]
@NYRI4 the fix I pushed in my PR fixes it on my end, let me know if it also works on yours.
![image](https://user-images.githubusercontent.com/19473034/142735862-0f317077-23ce-44e8-bce0-29481e8c1bf2.png)
