### ISSUE TITLE
Missing item icons when sticked to sidebar

### ISSUE THREAD

**Issue by Edick1337** [NYRI4/Comfy-spicetify#7]
Home, search and library buttons don't have their icons when they are sticked to sidebar

**Sticked**
![image](https://user-images.githubusercontent.com/20341452/142672930-e9515cc1-de4b-4e49-815a-dc5925a8b1a7.png)

**Unsticked**
![image](https://user-images.githubusercontent.com/20341452/142673062-2d982742-6045-4289-86c1-648cfed2cb57.png)

**Comment by Edick1337** [comment]
Also noticed that item icons are different depending on whether they are sticked or not

For example, lyrics icons when it's **sticked**
![image](https://user-images.githubusercontent.com/20341452/142673720-21c3b9a6-4741-4473-a80f-0c59cfe15afd.png)

**Unsticked**
![image](https://user-images.githubusercontent.com/20341452/142673784-8bcbab33-fac7-45f1-be3b-478ef1328c6c.png)

Same thing happens for library button

**Comment by NYRI4** [comment]
wdym by sticked or not ?

**Comment by Edick1337** [comment]
it got fixed by itself after git pull
maybe something was wrong with css map :D

by sticked or not i meant feature of spicetify to stick / unstick sidebar item 
![image](https://user-images.githubusercontent.com/20341452/142735021-11613a97-c037-4f82-80ea-7075cd2c7f62.png)
