### ISSUE TITLE
major changes in the theme

### ISSUE THREAD

**Issue by TheGeeKing** [NYRI4/Comfy-spicetify#9]
Is that intended @NYRI4 ?

![image](https://user-images.githubusercontent.com/58857539/142733899-363b722b-81fe-4efa-8cda-71b233fc3ebf.png)

is now

![image](https://user-images.githubusercontent.com/58857539/142733821-6e1efc65-9ef0-4bb0-aa17-fd65867daf9d.png)

**Comment by NYRI4** [comment]
#10

**Comment by TheGeeKing** [comment]
For users of spicetify 2.8.1 and lower, copy paste app.css in user.css

**Comment by Pukimaa** [comment]
Seems like just to be an ad from your Spotify Client (because you have no Premium)
